### PR TITLE
allow version tag besides latest

### PR DESCRIPTION
**Pull request by PhilippKuntschik**
pretty straightforward.

### CODE REVIEW

**Comment by fl42** [comment]
Hello,

Thanks for the PR

I would prefer to have the Dockerfile as a single source of truth and keep the building process as simple as `docker build -t nsd:latest .` (instead of having to check the nsd version in `.github/`)

What about extracting the nsd version from the Dockerfile in docker.yaml?
```sh
NSD_VERSION=$(grep "ARG NSD_VERSION" Dockerfile | cut -d= -f 2)
[ -z "$NSD_VERSION" ] && echo "Fail to extract nsd version from Dockerfile" && exit 1
```

**Comment by PhilippKuntschik** [comment]
I am fine with whatever provides a version number tag to the container in the registry. 

Are you able to push a commit to the merge request, or do you want to merge first, then add your code?

**Comment by fl42** [comment]
Fixed in master: ghcr.io/the-kube-way/nsd:v4.6.0 available
Thanks

**Comment by PhilippKuntschik** [comment]
Thanks a lot! 
May I suggest linking the container on the release page as with kube vip for example? Obviously not urgent. 

https://github.com/kube-vip/kube-vip/pkgs/container/kube-vip

**Pull request closed without merging**
